### PR TITLE
Add Travis CI tests for Node 4.4, 5.11, 6.0 and 6.1

### PR DESCRIPTION
**Pull request by calvinmikael**

### CODE REVIEW

**Comment by blakeembrey** [comment]
What do you think the value of these additions are? Seems like if this module broke under any version (barring normal unit tests, which is the reason to have some node versions) then JavaScript would be broken (since this module uses no specific node.js features other than remaining node 0.10 compatible).

**Comment by calvinmikael** [comment]
The value of the addition is the ability to update the tests for express.js.

As noted as a requirement by @dougwilson in https://github.com/expressjs/express/pull/2996

**Comment by dougwilson** [comment]
@calvinmikael to be clear, I never said you had to go and update the `.travis.yml` for all Express dependencies, only that we need to know they work first. This can easily be done locally by cloning repos, which is what I typically do.

**Comment by calvinmikael** [comment]
@dougwilson That makes the job much easier. Thanks for the clarification.

**Comment by blakeembrey** [comment]
@dougwilson Since this module obviously supports `6.x`, what would you prefer here?

@calvinmikael I'd prefer to remove some existing versions then. I don't think there's any need to run 6 tests for the same 100 lines of code. I think `0.10` and `stable` + `latest` might be good 👍

**Comment by dougwilson** [comment]
@blakeembrey it's hard to say. Typically the code team will makes the evaluations and manages Node.js version support policies, so when an external contributor tries to do it, it certainly makes it harder. I would only expect a full report from @calvinmikael that details the 6.x support of all the modules Express depends on. For example, @calvinmikael may write that "Express uses `array-flatten` 1.1.1, which is a basic JavaScript module without dependencies. It should have no issues running on any Node.js version, but I cloned the repo and ran it's test suite on Node.js 6.1.0 to be sure".

**Pull request closed without merging**
