### PR TITLE
Do not throw error for TypedArrays

### PR DESCRIPTION
**Pull request by dfcreative**
Hi @blakeembrey!

This tiny enhancement recognizes typed arrays instead of throwing error.

### CODE REVIEW

**Comment by blakeembrey** [comment]
What's the use-case of having `TypedArray`'s not error? Just wondering, seems like you'd just not run `arrayFlatten` on them.

**Comment by dfcreative** [comment]
One use case is [colormap](https://github.com/bpostlethwaite/colormap) module.
By default it returns nested colors, and it is handy to have them flattened.
But passing them to webgl requires array to be converted to Float32Array, as it is done in [gl-spectrum](https://github.com/audio-lab/gl-spectrum/blob/master/index.js#L308).
So here the same data can be stored as a nested array, plain array or typed array. And it would be really handy to call `flatten` to ensure any type of array-like data is flattened.

**Comment by dfcreative** [comment]
Though ok, the package is prefixed `array-`, and it has some old-node support, so maybe makes sense to leave it as is.
 I found that [flatten](https://npmjs.org/package/flatten) fits better for this use-case. Sorry for disturbing.

**Comment by blakeembrey** [comment]
@dfcreative If you want to flatten anything into an array, just call `flatten.from(...)`.

**Comment by dfcreative** [comment]
Ok, thanks. To my misfortune I did not read readme after main use-case.
Is there really a specific need for array-ish structures? What is the point of main entry then, except for checking that the argument is strictly an array? Some performance boost?

**Comment by blakeembrey** [comment]
No performance difference. It's there for developer UX. In case someone tries to use it with something unexpected (but works) like a string.

**Comment by dfcreative** [comment]
But the same may happen with `flatten.from`, how does...
Ok, array check does not justify 4 methods in API where there really should be one. And that is what makes UX, not the validation with fictive usefulness.
That is just opinion, nevermind.

**Comment by blakeembrey** [comment]
If you looked at the README, it's one method validated and one method not. I can't quite understand the rest of what you said, sorry.

**Pull request closed without merging**
